### ISSUE TITLE
Restricting word length to max 15

### ISSUE THREAD

**Issue by ghassanmas** [FACN4/KhanToDoList#13]
Why have you restricted the word length in the input field to be 15 chars max>? 

https://github.com/FACN4/KhanToDoList/blob/84d89bb643f0a9d44af71cab4bcb9a15f3eeba1d/index.html#L29

**Comment by DenisKent** [comment]
@ghassanmas The issue is I had to use: css:  word-wrap: break-word; to wrap text within the li elements. However, this doesn't work if there are no gaps in the text. I put in this rule to enforce gaps in the text. Is there a better way of doing this?
