### ISSUE TITLE
Button Sort by done

### ISSUE THREAD

**Issue by KatiaAsh** [FACN4/KhanToDoList#29]
What does this buttom do? Cuz for me it's doesn't work 🤔

**Comment by yoosefkh** [comment]
sort button is actually pushes the marked tasks to the bottom of the list 
example showing in the screen shots below.
![screenshot from 2018-07-12 11-41-23](https://user-images.githubusercontent.com/37940433/42622292-bb280ab6-85c8-11e8-8ff9-bbb36de17926.png)
![screenshot from 2018-07-12 11-41-46](https://user-images.githubusercontent.com/37940433/42622293-bb4f5904-85c8-11e8-9671-55b85221ff71.png)

**Comment by KatiaAsh** [comment]
I guess the problem for me 😅
Good job 👏🏻😂
I'll this issue now

**Comment by KatiaAsh** [comment]
<
